[package]
name = "mitte_arm"
version = "0.2.0"
authors = ["bytewise <bytewise@fastmail.com>"]
edition = "2018"

[dependencies]
mitte_core = { git = "https://github.com/bytwise/mitte_core", rev = "09e54d1" }

[dev-dependencies]
capstone = "0.10.0"
